"""
Audit memo skeleton generator.

Produces a Markdown audit-memo template pre-filled with the structured facts
from a CapTable + WaterfallResult + findings + resolutions list. Sections
that require analyst judgment are left as explicit `[ANALYST: ...]`
placeholders — the tool fills the structured-fact gaps, the analyst fills
the judgment gaps.

This artifact is the embodiment of the tool's positioning: the workpaper
that makes Evelyn's team faster without taking over their judgment.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Optional

from .checklist import Finding
from .models import CapTable, LPType
from .waterfall import WaterfallResult


def _money(v: Optional[float], symbol: str) -> str:
    if v is None:
        return "—"
    if abs(v) >= 1_000_000_000:
        return f"{symbol}{v/1_000_000_000:,.2f}B"
    if abs(v) >= 1_000_000:
        return f"{symbol}{v/1_000_000:,.2f}M"
    if abs(v) >= 1_000:
        return f"{symbol}{v/1_000:,.0f}K"
    return f"{symbol}{v:,.2f}"


def _commas(v: Optional[int]) -> str:
    if v is None:
        return "—"
    return f"{v:,}"


def _md(v) -> str:
    """Escape Markdown table-cell content.

    Pipe characters and newlines inside any field placed in a pipe table will
    corrupt the table render. Escape both. Called on every dynamic value
    inserted into a table cell.
    """
    if v is None:
        return "—"
    return str(v).replace("\\", "\\\\").replace("|", "\\|").replace("\n", " ").replace("\r", " ")


def build_audit_memo(
    cap_table: CapTable,
    waterfall: WaterfallResult,
    findings: list[Finding],
    resolutions: Optional[list[dict]] = None,
    generated_at: Optional[datetime] = None,
) -> str:
    """Return a Markdown audit memo skeleton.

    SD-AUD-M1: pass `generated_at` (typically engagement.created_at) to pin
    the cover timestamp. Without it the memo regenerates with wall-clock,
    matching the spec §8.10 carve-out but losing the byte-stability we get
    when sourcing the timestamp from a stored engagement field.
    """
    resolutions = resolutions or []
    sym = cap_table.company.currency_symbol
    co = cap_table.company

    lines: list[str] = []
    lines.append(f"# Audit Memo — {_md(co.name)}")
    lines.append("")
    lines.append(
        f"**Valuation date:** {co.valuation_date or '[ANALYST: confirm]'}  "
        f"**Currency:** {co.currency} ({sym})  "
        f"**Stage:** {co.stage or '—'}  "
        f"**Jurisdiction:** {co.jurisdiction or '—'}"
    )
    lines.append("")
    ts = (
        generated_at.astimezone(timezone.utc)
        if generated_at is not None
        else datetime.now(timezone.utc)
    )
    lines.append(
        f"*Generated by Cap Table Reconciler at "
        f"{ts.strftime('%Y-%m-%dT%H:%MZ')}. "
        f"This is a skeleton — analyst must fill `[ANALYST: ...]` placeholders "
        f"and supply judgment in the marked sections.*"
    )
    lines.append("")

    # 1. Capital structure
    lines.append("## 1. Capital structure")
    lines.append("")
    lines.append("| Class | Type | Shares | PPS | Issue date | Seniority | LP | Anti-dilution |")
    lines.append("|-------|------|-------:|----:|------------|----------:|----|---------------|")
    for sc in cap_table.share_classes:
        lp = sc.liquidation_preference
        if lp:
            lp_desc = f"{lp.multiple}x {lp.type.value.replace('_', ' ')}"
            if lp.cap_multiple:
                lp_desc += f" (cap {lp.cap_multiple}x)"
        else:
            lp_desc = "—"
        ad = (
            sc.anti_dilution.variant.value.replace("_", " ")
            if sc.anti_dilution and sc.anti_dilution.variant
            else "—"
        )
        rank = sc.seniority_rank if sc.type.value == "preferred" else "—"
        lines.append(
            f"| {_md(sc.name)} | {_md(sc.type.value)} | {_commas(sc.shares_outstanding)} | "
            f"{_money(sc.issue_price, sym) if sc.issue_price else '—'} | "
            f"{_md(sc.issue_date) if sc.issue_date else '—'} | {rank} | {_md(lp_desc)} | {_md(ad)} |"
        )
    lines.append("")
    lines.append(f"**Total fully-diluted shares (waterfall basis):** {_commas(cap_table.total_fully_diluted_for_waterfall)}")
    lines.append(f"**Aggregate liquidation preference overhang:** {_money(waterfall.lp_total, sym)}")
    lines.append("")

    # 2. Side letters
    if cap_table.side_letters:
        lines.append("## 2. Side letters")
        lines.append("")
        for sl in cap_table.side_letters:
            lines.append(f"### {sl.id} — {sl.title}")
            lines.append("")
            if sl.summary:
                lines.append(sl.summary)
                lines.append("")
            if sl.unresolved_questions:
                lines.append("**Open scope questions:**")
                for q in sl.unresolved_questions:
                    lines.append(f"- {q}")
                lines.append("")
            lines.append(
                f"**[ANALYST: confirm whether {sl.id} affects the present-date "
                f"waterfall, or only future-round modeling.]**"
            )
            lines.append("")

    # 3. SAFEs / Warrants
    if cap_table.safes_outstanding or cap_table.warrants_outstanding:
        lines.append("## 3. Convertibles and warrants")
        lines.append("")
        if cap_table.safes_outstanding:
            lines.append("**SAFEs outstanding:**")
            for s in cap_table.safes_outstanding:
                lines.append(f"- `{s.id}` — principal {_money(s.principal, sym)}, issued {s.issue_date or '—'}, cap {_money(s.valuation_cap, sym) if s.valuation_cap else '—'}")
            lines.append("")
        if cap_table.warrants_outstanding:
            lines.append("**Warrants outstanding:**")
            for w in cap_table.warrants_outstanding:
                lines.append(f"- `{w.id}` — {w.holder}: {_commas(w.shares)} {w.share_class} shares at strike {_money(w.strike_price, sym)}")
            lines.append("")
        lines.append("**[ANALYST: assess deep-ITM treatment for warrants and confirm SAFE conversion math against subsequent-round PPS.]**")
        lines.append("")

    # 4. Findings & resolutions
    lines.append("## 4. Gap-detection findings")
    lines.append("")
    blockers = [f for f in findings if f.severity == "blocker"]
    warnings = [f for f in findings if f.severity == "warning"]
    infos = [f for f in findings if f.severity == "info"]

    lines.append(
        f"Checklist returned **{len(blockers)} blocker(s), {len(warnings)} warning(s), "
        f"{len(infos)} info note(s)**. Findings are deterministic and rule-based; "
        f"the tool does not adjudicate — the table below is the analyst's working list."
    )
    lines.append("")
    if findings:
        lines.append("| Code | Severity | Summary |")
        lines.append("|------|----------|---------|")
        for f in findings:
            lines.append(f"| `{_md(f.code)}` | {_md(f.severity)} | {_md(f.summary)} |")
        lines.append("")
    if resolutions:
        lines.append("### Analyst resolutions applied in-session")
        lines.append("")
        for r in resolutions:
            lines.append(f"- **{_md(r['code'])}** — {_md(r['summary'])}")
        lines.append("")

    # 5. Waterfall breakpoints
    lines.append("## 5. Waterfall breakpoints")
    lines.append("")
    lines.append(
        "Each breakpoint is a separate strike for downstream OPM Backsolve. "
        "The tool stops at this list — fair-value computation is the analyst's step."
    )
    lines.append("")
    lines.append("| ID | Equity value | Event |")
    lines.append("|----|-------------:|-------|")
    for bp in waterfall.breakpoints:
        lines.append(f"| {_md(bp.id)} | {_money(bp.value, sym)} | {_md(bp.event)} |")
    lines.append("")

    # 6. Tranche allocation summary
    lines.append("## 6. Tranche allocation matrix")
    lines.append("")
    classes = [sc for sc in cap_table.share_classes if not sc.excluded_from_waterfall]
    header = "| Tranche | Range | " + " | ".join(_md(sc.name) for sc in classes) + " |"
    sep = "|---------|-------|" + "|".join(["---:" for _ in classes]) + "|"
    lines.append(header)
    lines.append(sep)
    for tr in waterfall.tranches:
        rng_high = _money(tr.range_high, sym) if tr.range_high is not None else "∞"
        rng = f"{_money(tr.range_low, sym)} → {rng_high}"
        cells = []
        for sc in classes:
            v = tr.marginal_allocation_pct.get(sc.name, 0.0)
            cells.append(f"{v:.1f}%")
        lines.append(f"| {_md(tr.id)} | {rng} | " + " | ".join(cells) + " |")
    lines.append("")

    # 7. Methodology disclosures
    lines.append("## 7. Methodology disclosures")
    lines.append("")
    parts = []
    cap_classes = [
        sc for sc in cap_table.preferred_classes_by_seniority
        if sc.liquidation_preference and sc.liquidation_preference.type == LPType.participating_capped
    ]
    full_ratchet_classes = [
        sc for sc in cap_table.preferred_classes_by_seniority
        if sc.anti_dilution and sc.anti_dilution.variant
        and sc.anti_dilution.variant.value == "full_ratchet"
    ]
    if cap_classes:
        names = ", ".join(sc.name for sc in cap_classes)
        parts.append(
            f"- **Participating-with-cap classes:** {names}. Each capped class "
            f"introduces additional breakpoints (cap-reach, pure-conversion). "
            f"Each is a separate strike in any OPM Backsolve."
        )
    if full_ratchet_classes:
        names = ", ".join(sc.name for sc in full_ratchet_classes)
        parts.append(
            f"- **Full-ratchet anti-dilution:** {names}. Confirm trigger status "
            f"(triggered by a subsequent down-round, or dormant). Where "
            f"triggered, the cap table reflects the post-trigger adjusted share "
            f"count; the conversion ratio is documented in the side-letter file."
        )
    dual_class = [sc for sc in cap_table.share_classes if sc.voting_differential]
    if dual_class:
        names = ", ".join(sc.name for sc in dual_class)
        parts.append(
            f"- **Dual-class voting:** {names}. Per VIMA / Cyril Amarchand "
            f"convention, classes with identical economic rights and voting "
            f"differentials are modeled as one economic class for waterfall "
            f"purposes."
        )
    if parts:
        lines.extend(parts)
    else:
        lines.append("- No methodology disclosures triggered by structure.")
    lines.append("")

    # 8. Analyst sign-off
    lines.append("## 8. Analyst sign-off")
    lines.append("")
    lines.append("- [ ] **[ANALYST: confirm all blockers above have been adjudicated.]**")
    lines.append("- [ ] **[ANALYST: confirm fair-value methodology selection (OPM / hybrid / DCF / market) and document peer-set basis.]**")
    lines.append("- [ ] **[ANALYST: confirm DLOM band (e.g., 25–35%) and basis (Finnerty, Chaffe, restricted-stock studies).]**")
    lines.append("- [ ] **[ANALYST: confirm subsequent events through the report date.]**")
    lines.append("")
    lines.append("*Prepared by:* `[ANALYST NAME]`, `[DATE]`")
    lines.append("*Reviewed by:* `[REVIEWER NAME]`, `[DATE]`")
    lines.append("")

    return "\n".join(lines)
